#k0s-configs/k0sctl.yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
    - role: controller
      ssh:
        address: 192.168.1.123
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa_ssh.pub
      installFlags:
        - --enable-worker    # запускаем kubelet и на контроллере
    - role: worker
      ssh:
        address: 192.168.1.124
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa_ssh.pub

  k0s:
    version: v1.32.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s-cluster
      spec:
        network:
          provider: kuberouter
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12

        # Добавляем секцию Helm-расширений
        extensions:
          helm:
            # Список репозиториев, которые будут добавлены
            repositories:
              - name: stable
                url: https://charts.helm.sh/stable
              - name: prometheus-community
                url: https://prometheus-community.github.io/helm-charts
              - name: traefik
                url: https://traefik.github.io/charts
              - name: nats
                url: https://nats-io.github.io/k8s/helm/charts/
            # Список чартов для установки
            charts:
              - name: nats-js
                chartname: nats/nats
                version: "1.3.6"
                namespace: messaging
                values: |
                  jetstream:
                    enabled: true       # включаем JetStream в NATS-сервере
                    max_mem_store: 1GB
                    max_file_store: 10GB
                  server:
                    replicas: 1
                    storage:
                      type: file
                      size: 5Gi        # настраиваем постоянное хранилище для JetStream
                  persistence:
                    enabled: true
                    storageClass: local-path      # Явно указываем StorageClass
                    size: 5Gi
              # Prometheus Stack
              - name: prometheus-stack
                chartname: prometheus-community/prometheus
                version: "31.0.0"
                namespace: monitoring
                values: |
                  alertmanager:
                    enabled: false
                  server:
                    persistentVolume:
                      enabled: false

              # Traefik Ingress Controller
              - name: traefik-ingress
                chartname: traefik/traefik
                version: "20.7.2"
                namespace: kube-system
                values: |
                  service:
                    type: NodePort
                    nodePorts:
                      http: "30080"
                      https: "30443"
