# nats-broker/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-broker
  labels:
    app: nats-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-broker
  template:
    metadata:
      labels:
        app: nats-broker
    spec:
      containers:
        - name: nats
          image: nats:latest
          args: ["-c", "/etc/nats/nats-server.conf"]
          ports:
            - containerPort: 4222  # клиентский порт
            - containerPort: 8222  # мониторинг / HTTP
          volumeMounts:
            - name: config
              mountPath: /etc/nats
            - name: jetstream-data
              mountPath: /data/jetstream
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: config
          configMap:
            name: nats-config
            items:
              - key: nats-server.conf
                path: nats-server.conf
        - name: jetstream-data
          persistentVolumeClaim:
            claimName: nats-jetstream-pvc
