### nats-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nats-client
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitor
    port: 8222
    targetPort: 8222

---
apiVersion: v1
kind: Service
metadata:
  name: nats-cluster
  namespace: default
spec:
  clusterIP: None
  selector:
    app: nats
  ports:
  - name: cluster
    port: 6222
    targetPort: 6222
