### nats-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: default
spec:
  serviceName: nats-client
  replicas: 3
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.9.27
        args:
        - "/nats-server"
        - "--config"
        - "/etc/nats/nats-server.conf"
        ports:
        - name: client
          containerPort: 4222
        - name: monitor
          containerPort: 8222
        volumeMounts:
        - name: data
          mountPath: /data/jetstream
        - name: config
          mountPath: /etc/nats
          readOnly: true
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nats --server 127.0.0.1:4222 server check"
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: nats-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nats-jetstream-sc
      resources:
        requests:
          storage: 10Gi
