apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-service
  labels:
    app: relay-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relay-service
  template:
    metadata:
      labels:
        app: relay-service
    spec:
      containers:
        - name: relay
          image: yourregistry/relay-service:latest
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: "nats://nats-broker:4222"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName  # Downward API для уникальности инстанса :contentReference[oaicite:0]{index=0}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
