apiVersion: v1
kind: Service
metadata:
  name: relay-service
  labels:
    app: relay-service
spec:
  selector:
    app: relay-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
