# relay-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: relay-service
  labels:
    app: relay-service
spec:
  # Headless: нет ClusterIP, DNS создаёт запись на каждый Pod
  clusterIP: None
  selector:
    app: relay-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
