# relay-service/statefullset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-service
spec:
  serviceName: "relay-service"       # может быть любым, лишь бы совпадало с selector
  replicas: 2
  selector:
    matchLabels:
      app: relay-service
  template:
    metadata:
      labels:
        app: relay-service
    spec:
      containers:
        - name: relay
          image: ghcr.io/dmitrij-solovjev/distributed-smart-home-cluster/relay-service:latest
          env:
            - name: NATS_URL
              value: "nats://nats-js.messaging.svc.cluster.local:4222"  # имя сервиса от Helm-чарта NATS :contentReference[oaicite:7]{index=7}
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
