# relay-service/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-service
spec:
  serviceName: "relay-service"   # Должно совпадать с именем headless Service
  replicas: 2
  selector:
    matchLabels:
      app: relay-service
  template:
    metadata:
      labels:
        app: relay-service
    spec:
      containers:
      - name: relay
        image: ghcr.io/dmitrij-solovjev/distributed-smart-home-cluster/relay-service:latest
        env:
          - name: NATS_URL
            value: "nats://my-nats:4222"
          - name: NODE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - name: http
            containerPort: 8080
      restartPolicy: Always
