name: CI/CD for relay-service

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  # 1. Run Pytest suite
  test:
    name: Test Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

  # 2. Build and publish a temporary 'test' image tag
  build-test:
    name: Build & Push Test Image
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build test image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/relay-service:test
          docker build -t $IMAGE .

      - name: Push test image
        run: |
          docker push $IMAGE

  # 3. Run container smoke test
  smoke:
    name: Smoke Test Container
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Pull test image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/relay-service:test
          docker pull $IMAGE

      - name: Run container smoke test
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/relay-service:test
          docker run --rm $IMAGE python -c "import your_entrypoint_module; print('OK')"

  # 4. Publish final image with semantic versioning
  publish:
    name: Publish Image
    needs: smoke
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Determine next version
        id: version
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=relay-service
          LATEST=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /orgs/$OWNER/packages/container/$REPO/versions \
            --jq '.[0].metadata.container.tags[0]' 2>/dev/null || echo "0.1.0")
          echo "Current version: $LATEST"
          IFS='.' read MAJOR MINOR PATCH <<< "$LATEST"
          PATCH=$((PATCH + 1))
          NEXT="$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEXT" >> $GITHUB_ENV

      - name: Build final image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/relay-service:${{ env.NEW_VERSION }}
          docker build -t $IMAGE .

      - name: Push final image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/relay-service:${{ env.NEW_VERSION }}
          docker push $IMAGE
