name: CI/CD for relay-service

on:
  push:
    paths:
      - 'relay-service/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read         # чтение контента репозитория
  packages: write       # разрешение на запись в GitHub Container Registry

jobs:
  # 1. Run Pytest suite
  test:
    name: Test Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

  # 2. Build and push a temporary 'test' image to GHCR
  build-test:
    name: Build & Push Test Image
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push test image
        run: |
          IMAGE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service:test
          docker build -t $IMAGE .
          docker push $IMAGE

  # 3. Run container smoke test
  smoke:
    name: Smoke Test Container
    needs: build-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull and test container
        run: |
          IMAGE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service:test
          docker pull $IMAGE
          # TODO: Replace with real smoke tests
          #docker run --rm $IMAGE python -c "import your_entrypoint_module; print('OK')"

  # 4. Tag test image as version and push
  publish:
    name: Publish Image
    needs: smoke
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Determine next semantic version
        id: calc_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}                                     # Dmitrij-Solovjev/distributed-smart-home-cluster
          PACKAGE: distributed-smart-home-cluster%2Frelay-service            # URL-encoded имя пакета
        run: |
          # 1) Получаем все версии из Container registry
          tags_json=$(gh api \
            /repos/${REPO}/packages/container/${PACKAGE}/versions \
            --paginate \
            -q '.[] | {version: .metadata.container.tags[]}')

          # 2) Извлекаем массив тегов версиями X.Y.Z
          versions=$(printf '%s\n' "$tags_json" \
            | jq -r '.version' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' || true)

          if [ -z "$versions" ]; then
            # если пакетов нет — стартуем с 0.1.0
            next="0.1.0"
          else
            # 3) Сортируем по семантике и берём максимальный
            max=$(printf '%s\n' $versions | sort -V | tail -n1)

            # 4) Раскладываем на части и увеличиваем патч
            IFS='.' read -r major minor patch <<< "$max"
            next="${major}.${minor}.$((patch + 1))"
          fi

          echo "Determined next version: $next"
          # 5) Экспортируем в GITHUB_ENV
          echo "NEW_VERSION=$next" >> $GITHUB_ENV


      - name: Pull, tag and push versioned image
        run: |
          BASE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service
          docker pull $BASE:test
          docker tag $BASE:test $BASE:${{ env.NEW_VERSION }}
          docker push $BASE:${{ env.NEW_VERSION }}
