name: CI/CD Relay Service

on:
  push:
    # Триггерим только при изменениях в папке relay-service/
    paths:
      - 'relay-service/**'

permissions:
  contents: write    # чтобы github-tag-action мог пушить теги
  packages: write    # чтобы пушить Docker-образы

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужны все теги для bump-а

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dev dependencies
        working-directory: relay-service
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt pytest pytest-asyncio

      - name: Build Docker image (test)
        run: |
          IMAGE=test-${{ github.sha }}
          docker build \
            --file relay-service/Dockerfile \
            --tag "${IMAGE}" \
            relay-service
        env:
          DOCKER_BUILDKIT: 1

      - name: Run tests inside container
        run: |
          docker run --rm "${{ steps.build.outputs.IMAGE }}" pytest
        # (если нужно, задайте volume или другие флаги)

      - name: Bump patch version & create Git tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
          INITIAL_VERSION: 0.1.1

      - name: Set VERSION env
        run: echo "VERSION=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Build Docker image (release)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/relay-service:${{ env.VERSION }}
          docker build \
            --file relay-service/Dockerfile \
            --tag "${IMAGE_NAME}" \
            relay-service
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push release image
        run: |
          docker push ghcr.io/${{ github.repository }}/relay-service:${{ env.VERSION }}
