name: CI/CD for relay-service

on:
  push:
    paths:
      - 'relay-service/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read         # чтение контента репозитория
  packages: write       # разрешение на запись в GitHub Container Registry

jobs:
  # 1. Run Pytest suite
  test:
    name: Test Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

  # 2. Build and push a temporary 'test' image to GHCR
  build-test:
    name: Build & Push Test Image
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push test image
        run: |
          IMAGE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service:test
          docker build -t $IMAGE .
          docker push $IMAGE

  # 3. Run container smoke test
  smoke:
    name: Smoke Test Container
    needs: build-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull and test container
        run: |
          IMAGE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service:test
          docker pull $IMAGE
          # TODO: Replace with real smoke tests
          #docker run --rm $IMAGE python -c "import your_entrypoint_module; print('OK')"

  # 4. Tag test image as version and push
  publish:
    name: Publish Image
    needs: smoke
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: relay-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Determine next version
        id: version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            // Собираем "namespace" пакета: repo/relay-service и кодируем слэш
            const pkgName = `${repo}/relay-service`;
            const encoded = encodeURIComponent(pkgName); // => "distributed-smart-home-cluster%2Frelay-service" :contentReference[oaicite:3]{index=3}
            const per_page = 100;
            let versions = [];

            // Пагинируем запрос
            for (let page = 1; ; page++) {
              const res = await github.request(
                `GET /repos/${owner}/${repo}/packages/container/${encoded}/versions`, {
                  per_page,
                  page
                }
              );
              if (res.data.length === 0) break;
              versions.push(...res.data);
            }

            // Извлекаем все теги, отвечающие SemVer 2.0.0
            const semverTags = versions
              .flatMap(v => v.metadata.container.tags)
              .filter(t => /^\d+\.\d+\.\d+$/.test(t)); // Только чистые 1.2.3 :contentReference[oaicite:4]{index=4}

            // Сортируем естественным порядком и берём последний
            semverTags.sort((a, b) => a.split('.').map(Number).reduce((d, v, i) => d || (v - b.split('.')[i]), 0));
            const latest = semverTags.pop() || '0.0.0';
            const [M, m, p] = latest.split('.').map(Number);
            const next = `${M}.${m}.${p + 1}`;

            core.exportVariable('NEW_VERSION', next);
            core.info(`Determined next patch version: ${next}`);


      - name: Pull, tag and push versioned image
        run: |
          BASE=ghcr.io/${{ env.OWNER_LOWER }}/distributed-smart-home-cluster/relay-service
          docker pull $BASE:test
          docker tag $BASE:test $BASE:${{ env.NEW_VERSION }}
          docker push $BASE:${{ env.NEW_VERSION }}
